"""empty message

Revision ID: c97554de9c9d
Revises: d45db36b45a1
Create Date: 2023-03-05 22:06:53.617115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c97554de9c9d'
down_revision = 'd45db36b45a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokedex',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('poke_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['poke_id'], ['pokemon.id'], )
    )
    op.drop_constraint('pokemon_user_id_fkey', 'pokemon', type_='foreignkey')
    op.drop_column('pokemon', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pokemon', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pokemon_user_id_fkey', 'pokemon', 'user', ['user_id'], ['id'])
    op.drop_table('pokedex')
    # ### end Alembic commands ###
